name: GenDungeon
version: '${version}'
description: ${description}
main: com.example.gendungeonasync.GenDungeonAsync
api-version: '1.21'
author: YourName

commands:
  gendungeon:
    description: Generate a random dungeon
    usage: /gendungeon [size] [difficulty]
    permission: gendungeon.create
    aliases: [dg, gen, dungeon]
  
  dungeontp:
    description: Teleport to a generated dungeon
    usage: /dungeontp <player> <dungeon_id>
    permission: gendungeon.teleport
    aliases: [dtp]
  
  dungeonleave:
    description: Leave your current dungeon
    usage: /dungeonleave
    permission: gendungeon.create
    aliases: [dleave, dexit]

permissions:
  gendungeon.*:
    description: All dungeon permissions
    children:
      gendungeon.create: true
      gendungeon.teleport: true
      gendungeon.admin: true
  
  gendungeon.create:
    description: Allow creating dungeons
    default: true
  
  gendungeon.teleport:
    description: Allow teleporting to dungeons
    default: op
  
  gendungeon.admin:
    description: Admin permissions for dungeon management
    default: op
